# Generated by Django 4.1.7 on 2023-06-19 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConformationalEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('smiles', models.CharField(blank=True, max_length=500)),
                ('cas_ids', models.TextField(blank=True)),
                ('molecule_name', models.CharField(blank=True, max_length=500)),
                ('database_id', models.CharField(blank=True, max_length=500)),
                ('svg_file', models.FileField(blank=True, upload_to='svg_files')),
                ('mol_file', models.FileField(blank=True, upload_to='mol_files')),
                ('computational_method', models.ManyToManyField(blank=True, to='file_storage.computationalmethod')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('num_indices', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('conformational_ensembles', models.ManyToManyField(to='file_storage.conformationalensemble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('smiles', models.CharField(blank=True, max_length=500)),
                ('log_file', models.FileField(blank=True, upload_to='log_files')),
                ('ComputationalMethods', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('conformational_ensembles', models.ManyToManyField(blank=True, to='file_storage.conformationalensemble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnsembleParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices', models.JSONField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('conformational_ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_storage.conformationalensemble')),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_storage.parametertype')),
            ],
        ),
        migrations.AddField(
            model_name='conformationalensemble',
            name='conformers',
            field=models.ManyToManyField(blank=True, to='file_storage.molecule'),
        ),
        migrations.AddField(
            model_name='conformationalensemble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
